.TH A2I 1 "July 2024" "A2I Manual" "A2I Manual"
.SH NAME
a2i \- audio to image visualizer
.SH SYNOPSIS
.B a2i
.RI <audiofile> " [<args>]"
.br
.B a2i config
.RI <subcommand> " [<args>] [<flags>]"
.br
.B a2i mic
.RI "[<flags>]"
.SH DESCRIPTION
.B a2i
is a fast tool to visualize audio spectrum and listen music.
.SH COMMANDS
.TP
.B a2i <audiofile>
Configure settings for a2i.
.TP
.B a2i config
Configure settings for a2i.
.TP
.B a2i mic
Use microphone for audio input.
.SH "SEE ALSO"
.BR a2i-config (1),
.BR a2i-mic (1)
